version: "3"

services:
  db:
    hostname: mariaDB
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - LANG=C.UTF-8
    restart: always
  
  web:
    hostname: web
    build: .
    command: sh -c "sleep 3; ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    tty: true
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - db
